# Generated by Django 5.1.6 on 2025-02-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_person_shart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='shart_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1),
        ),
    ]
