# Generated by Django 5.1.6 on 2025-02-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_person_shart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shart_color',
            field=models.CharField(choices=[('B', 'Black'), ('R', 'Red'), ('W', 'White')], default='Zero', max_length=1),
            preserve_default=False,
        ),
    ]
