# Generated by Django 5.1.6 on 2025-02-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_fruit_delete_runner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='name',
            new_name='F_name',
        ),
        migrations.RemoveField(
            model_name='fruit',
            name='id',
        ),
        migrations.AddField(
            model_name='fruit',
            name='S_name',
            field=models.CharField(default='Zero', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
