# Generated by Django 5.1.6 on 2025-02-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_rename_name_fruit_f_name_remove_fruit_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fFruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sFruit',
            fields=[
                ('S_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
