# Generated by Django 5.1.6 on 2025-02-23 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_roll_delete_ffruit_delete_sfruit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='roll',
            new_name='troll',
        ),
    ]
