# Generated by Django 5.2.5 on 2025-08-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coreapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'oxen',
                'ordering': ['nm'],
            },
        ),
    ]
