# Generated by Django 5.2.5 on 2025-08-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreapp',
            options={'ordering': ['nm', 'tech'], 'verbose_name': 'technology', 'verbose_name_plural': 'Name'},
        ),
        migrations.AddField(
            model_name='coreapp',
            name='tech',
            field=models.CharField(default='zero', max_length=50),
            preserve_default=False,
        ),
    ]
