# Generated by Django 5.2.5 on 2025-08-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_coreapp_options_coreapp_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='coreapp2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'technology',
                'ordering': ['tech'],
            },
        ),
        migrations.AlterModelOptions(
            name='coreapp',
            options={'ordering': ['nm'], 'verbose_name_plural': 'Name'},
        ),
        migrations.RemoveField(
            model_name='coreapp',
            name='tech',
        ),
    ]
