# Generated by Django 5.2.5 on 2025-08-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_coreapp2_alter_coreapp_options_remove_coreapp_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='coreapp1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=500)),
            ],
        ),
    ]
