# Generated by Django 5.1.6 on 2025-04-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product_master',
                'ordering': ['-created_at'],
                'permissions': [('can_mark_featured', 'Can mark product as featured')],
                'unique_together': {('name', 'created_at')},
            },
        ),
    ]
